/proc/RunTest()
	var/first = noise_hash(1, 2, 3)
	var/second = noise_hash(1, 2, 3)
	var/from_list = noise_hash(list(1, 2, 3))
	var/named = noise_hash("default", 1, 2, 3)
	var/different = noise_hash(3, 2, 1)

	ASSERT(isnum(first))
	ASSERT(first >= 0)
	ASSERT(first < 1)
	ASSERT(first == second)
	ASSERT(first == from_list)
	ASSERT(first == named)
	ASSERT(first != different)
