/proc/RunTest()
	ASSERT((1 <=> 2) == -1)
	ASSERT((2 <=> 1) == 1)
	ASSERT((2 <=> 2) == 0)
	ASSERT(("a" <=> "b") == -1)
	ASSERT(("b" <=> "a") == 1)
	ASSERT(("a" <=> "a") == 0)
	ASSERT((null <=> 0) == 0)
	ASSERT((0 <=> null) == 0)
	ASSERT((null <=> 1) == -1)
	ASSERT((null <=> "") == 0)
